In [2]:
# Pandas Series and DataFrame concept()
import numpy as np
import pandas as pd

In [6]:
my_list = [123, 234, 345]
x = np.array(my_list)
x

array([123, 234, 345])

In [7]:
type(x)

numpy.ndarray

In [8]:
y = pd.Series(my_list)

In [9]:
index_value = ['high', 'middle', 'low']
one = pd.Series(data = my_list, index = index_value)
one

high      123
middle    234
low       345
dtype: int64

In [10]:
index_value1 = ['first', 'second', 'third']
two = pd.Series(data = my_list, index = index_value1)
two

first     123
second    234
third     345
dtype: int64

In [11]:
ice_cream = [['mango',1],['apple',2],['strawberry',3]]
df = pd.DataFrame(data = ice_cream, index = ['good', 'ok', 'plain'], columns = ['name','score'])

In [ ]:
# Read file
# pd.read_csv(r"url", columns = ['name1', 'name2', 'name3'])
# pd.read_excel()
# pd.read_json()

In [ ]:
# df = df.rename(columns={'old1': 'new1', 'old2': 'new2'})
# df.rename(columns={'old1': 'new1'}, inplace=True)
# df.columns = ['new1', 'new2', 'new3']  # 必须给出所有列名，顺序对应

In [ ]:
# # Data filter
# .contains('string') method is used to check if each element in a Series contains a specified string or pattern. This method is particularly useful when you want to filter rows based on whether a specific substring exists in the values of a column.

# .str.startswith() method is used to check if each element in a Series starts with a specified string.

# .str.endswith() method is used to check if each element in a Series ends with a specified string.

# .duplicated() method is used to identify duplicate rows in a DataFrame

# .str.match() method is used to check if each element in a Series matches a specified regular expression pattern

In [ ]:
# These functions are extremely useful to manipulate and use date columns within a Pandas Dataframe. Here are some of the most common ones you'll use:

# pd.to_datetime() function is used to convert an object to a datetime object

# .dt.year is used to extract the year component from a datetime-like Series

# .dt.day is used to extract the day component

# .dt.day_name() is used to extract the name of the day of the week and is particularly useful when you want to analyze or categorize data based on the day of the week.

In [ ]:
df.sort_values(by = [], axis=0, ascending=True, inplace=False, kind='quicksort', na_position='last', ignore_index=False, key=None)

In [ ]:
df.set_index(['col_name1','col_name2']).sort_values(by = ['col_name1','col_name2'], ascending = [True, False])
# will NOT be unique!!!!!!

df.reset_index(inplace = True)
df.swaplevel('col_name2', 'col_name1')

In [ ]:
df.pivot(index = '', columns = '', values = '')
# will NOT be transformed to unique!!!!!!
# function, object, .method(parameter), slice

In [ ]:
df.groupby('col1')['col2'].median().sort_values(ascending = True)
df.groupby('col1').agg({'outstanding':['sum', 'count']}) #MULTIPLE aggregation
df.groupby('col1').agg(sum_balance = ('outstanding','sum'), count_balance = ('outstanding', 'count'))
df[df['col_1'] == 'management'].groupby(['col_2', 'col_3'])['outstanding'].sum()
# similar to windows function to transform
df['col_new'] = df[df['col_1'] == 'yes'].groupby('col_2')['outstanding'].transform('mean')
df_usa.pivot_table(index = 'job_posted_month', columns = 'job_title_short', aggfunc = 'size')

In [3]:
#  MERGE AND JOIN
data1 = {
    'employee_id': [1, 2, 3, 4, 5, 6, 7, 8],
    'name': ['Michael Scott', 'Jim Halpert', 'Pam Beesly', 'Dwight Schrute', 'Angela Martin', 'Kevin Malone', 'Oscar Martinez', 'Stanley Hudson'],
    'job_title': ['Regional Manager', 'Sales Representative', 'Receptionist', 'Assistant to the Regional Manager', 'Head of Accounting', 'Accountant', 'Accountant', 'Sales Representative'],
    'salary': [100000, 60000, 55000, 65000, 60000, 55000, 55000, 60000]
}

df1 = pd.DataFrame(data1)

data2 = {
    'employee_id': [1, 2, 3, 5, 6, 7, 8, 9],
    'name': ['Michael Scott', 'Jim Halpert', 'Pam Beesly', 'Angela Martin', 'Kevin Malone', 'Oscar Martinez', 'Stanley Hudson', 'Phyllis Vance'],
    'department': ['Management', 'Sales', 'Reception', 'Accounting', 'Accounting', 'Accounting', 'Sales', 'Sales']
}

df2 = pd.DataFrame(data2)

In [4]:
df1

   employee_id            name                          job_title  salary
0            1   Michael Scott                   Regional Manager  100000
1            2     Jim Halpert               Sales Representative   60000
2            3      Pam Beesly                       Receptionist   55000
3            4  Dwight Schrute  Assistant to the Regional Manager   65000
4            5   Angela Martin                 Head of Accounting   60000
5            6    Kevin Malone                         Accountant   55000
6            7  Oscar Martinez                         Accountant   55000
7            8  Stanley Hudson               Sales Representative   60000

In [5]:
df2

   employee_id            name  department
0            1   Michael Scott  Management
1            2     Jim Halpert       Sales
2            3      Pam Beesly   Reception
3            5   Angela Martin  Accounting
4            6    Kevin Malone  Accounting
5            7  Oscar Martinez  Accounting
6            8  Stanley Hudson       Sales
7            9   Phyllis Vance       Sales

In [6]:
df1.merge(df2, how = 'inner', left_on = 'employee_id', right_on = 'employee_id')

,employee_id,name_x,job_title,salary,name_y,department
0,1,Michael Scott,Regional Manager,100000,Michael Scott,Management
1,2,Jim Halpert,Sales Representative,60000,Jim Halpert,Sales
2,3,Pam Beesly,Receptionist,55000,Pam Beesly,Reception
3,5,Angela Martin,Head of Accounting,60000,Angela Martin,Accounting
4,6,Kevin Malone,Accountant,55000,Kevin Malone,Accounting
5,7,Oscar Martinez,Accountant,55000,Oscar Martinez,Accounting
6,8,Stanley Hudson,Sales Representative,60000,Stanley Hudson,Sales

In [7]:
pd.merge(df1, df2, on = 'employee_id', how = 'outer', suffixes = ('_left','_right'), indicator = True)

,employee_id,name_left,job_title,salary,name_right,department,_merge
0,1,Michael Scott,Regional Manager,100000.0,Michael Scott,Management,both
1,2,Jim Halpert,Sales Representative,60000.0,Jim Halpert,Sales,both
2,3,Pam Beesly,Receptionist,55000.0,Pam Beesly,Reception,both
3,4,Dwight Schrute,Assistant to the Regional Manager,65000.0,NaN,NaN,left_only
4,5,Angela Martin,Head of Accounting,60000.0,Angela Martin,Accounting,both
5,6,Kevin Malone,Accountant,55000.0,Kevin Malone,Accounting,both
6,7,Oscar Martinez,Accountant,55000.0,Oscar Martinez,Accounting,both
7,8,Stanley Hudson,Sales Representative,60000.0,Stanley Hudson,Sales,both
8,9,NaN,NaN,NaN,Phyllis Vance,Sales,right_only

In [ ]:
pd.merge(df1, df2, on = 'employee_id', how = 'left').merge(df3, how = 'left', on = 'department_id')

In [ ]:
pd.concat([df1, df2])#stack vertically as default

In [ ]:
df.plot(x = 'col_1', y = 'col_2', kind = 'bar')

In [ ]:
import matplotlib.pyplot as plt

plt.figure(figsize=(20, 5))
plt.plot(x, y, label = 'name', color = 'blue', marker = '^', markersize = 10, linestyle = '--', markeredgecolor = 'green')
plt.title('name')
plt.xlabel('X axis')
plt.ylabel('Y axis')

plt.xticks([1,2,3])
plt.yticks([0, 5, 10, 15, 20])
plt.legend()

plt.show()

In [ ]:
import seaborn as sns
import numpy as np

sns.barplot(df_filtered, x = "col_1", y = "col_2", estimator = 'mean')
plt.plot()

In [ ]:
#DATA CLEANING
df.drop_duplicates(subset = ['First_name', 'Last_name'], keep = 'last')
df['Column_1'].str.replace(r"\D", "")
df['full_name'].str.split('', 1, expand = True)
df.dropna(subset = [''])
df.dropna(how = 'all')
df.dropna(how = 'any')
df['column'].fillna(df['column'].mean())
df['column'].fillna(method = 'ffill')
df['column'].fillna(method = 'bfill')

df['column'].replace(np.nan, 'Unknown')
df['last_name'] = df['last_name'].group(['first_name','house'])['last_name'].transform('first')

In [ ]:
# correlation heatmap
df_corr = df.corr(method = 'person')
df_corr = df.corr(method = 'spearman')
sns.heatmap(df_corr, annot = True, cmap = 'coolwarm')
# .cov() cannot present standardized data

In [ ]:
# Linear regression at a glance
sns.scatterplot(data = MSRP, x = 'Engine HP', y = 'MSRP')

sns.regplot(data = MSRP, x = 'Engine HP', y = 'MSRP', scatter = False, color = 'red')

plt.show()

In [ ]:
# Time series data aggregated by specified time range 'D', 'M', 'Q', 'Y'. 'H', 'min'
df_new = df.resample('D').count()
# relevant visualization
plt.plot(df_new.index, df_new['col_name'])
plt.show()

In [ ]:
#         !!!!!!   Mutiple replacement AND then combine them together if they are mutual exclusive
food['marital_Divorced'] = food['marital_Divorced'].replace({1:5, 0:0})
food['marital_Married'] = food['marital_Married'].replace({1:4,0:0})
food['marital_Single'] = food['marital_Single'].replace({1:3,0:0})
food['marital_Together'] = food['marital_Together'].replace({1:2,0:0})
food['marital_Widow'] = food['marital_Widow'].replace({1:1,0:0})

food['marital_status'] = food[['marital_Divorced','marital_Married','marital_Single','marital_Together','marital_Widow']].sum(axis = 1)

In [ ]:

# Split one column(list data type) and then stack data vertically without adding another hierachy
# But increased granularity
split = movies['genres'].str.split('|').explode()
# Raw data frequently appear when recieving data from API/JSON file

### section summary
1. pandas operation are mostly about columns data 
2. groupby()['col_name'].agg() will decrease the granularity of dataset
3. str.split(' ').explode() will increase the granularity
4. cross join tables is a process of cross matching and the result table has the same granularity of the table that has the biggest granularity
5. when visulize pivot table, only values will be y axis